name: Sync with upstream template

on:
  schedule:
    - cron: "0 0 * * 6" # Weekly on Saturday
  workflow_dispatch:

env:
  UPSTREAM_BRANCH: main
  UPSTREAM_REPO: caffeine-addictt/template

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.repository != env.UPSTREAM_REPO
        # https://github.com/actions/checkout#usage
        with:
          # uncomment if you use submodules within the source repository
          # submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        if: github.repository != env.UPSTREAM_REPO
        with:
          # We need "workflows" permissions to allow us to update .github/workflows/*
          # Create a PAT with "contents:write", "workflows:write" and "metadata:read" permissions
          # and write it to the "PERSONAL_ACCESS_TOKEN" secret
          # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token
          # https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          source_repo_path: ${{ env.UPSTREAM_REPO }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          pr_labels: "CI: Template Sync"
